# Project identification
sonar.projectKey=netflix-clone
sonar.projectName=Netflix Clone NodeJS
sonar.projectVersion=1.0

# Source code directory
sonar.sources=src

# Exclude non-code folders
sonar.exclusions=**/node_modules/**,**/src/public/**

# Encoding
sonar.sourceEncoding=UTF-8

# JavaScript coverage (optional – safe to keep)
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Test file exclusions (if no tests)
sonar.test.exclusions=**/*.test.js,**/*.spec.js

# Dockerfile analysis
sonar.dockerfile.path=Dockerfile

