apiVersion: apps/v1
kind: Deployment
metadata:
  name: NodeJs-app
  labels:
    app: Netflix-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: Netflix-app
  template:
    metadata:
      labels:
        app: Netflix-app
    spec:
      containers:
      - name: Netflix-app
        image: 076226033208.dkr.ecr.ap-south-1.amazonaws.com/netflix-app:2473bfba1b86b83b09daeaf93934fcaa5e4e191a
        ports:
        - containerPort: 3000
          #ismail