apiVersion: apps/v1
kind: Deployment
metadata:
  name: NodeJs-app
  labels:
    app: Netflix-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: Netflix-app
  template:
    metadata:
      labels:
        app: Netflix-app
    spec:
      containers:
      - name: Netflix-app
        image: 076226033208.dkr.ecr.ap-south-1.amazonaws.com/netflix-app:20b3169f8017a5a7b0adf6c4d17269b27a3f5bea
        ports:
        - containerPort: 3000
          #ismail